blog/urls.py
from django.urls import path
from blog.views import PostListView, PostDetailView


app_name = 'blog'
urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('<str:post_month>/<str:post_slug>', PostDetailView.as_view(), name='post'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="index.html")),
    path('accounts/', include('accounts.urls')),
    path('', include('core.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
    urlpatterns += [
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from core.models import BaseModel
from django.utils.text import slugify

from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFill

from accounts.models import User
from django.utils.translation import gettext as _


class Tag(BaseModel):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class PostCategory(BaseModel):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Post categories'

    def __str__(self):
        return self.name


class Image(BaseModel):
    BLOG_MEDIA_FOLDER = 'blog_images'

    IMAGE_SIZE_X = 600 # pixels
    IMAGE_SIZE_Y = 400 # pixels
    IMAGE_QUALITY = 100 # percent
    IMAGE_FORMAT = 'JPEG'

    THUMBNAIL_SIZE_X = 100 # pixels
    THUMBNAIL_SIZE_Y = 50 # pixels
    THUMBNAIL_QUALITY = 60 # percent
    THUMBNAIL_FORMAT = 'JPEG'

    image = ProcessedImageField(
        upload_to=BLOG_MEDIA_FOLDER,
        format=IMAGE_FORMAT,
        processors=[ResizeToFill(IMAGE_SIZE_X, IMAGE_SIZE_Y)],
        options={'quality': IMAGE_QUALITY},
        null=True,
        blank=True
    )
    image_thumbnail = ImageSpecField(
        source='image',
        processors=[ResizeToFill(THUMBNAIL_SIZE_X, THUMBNAIL_SIZE_Y)],
        format=THUMBNAIL_FORMAT,
        options={'quality': THUMBNAIL_QUALITY})

    def __str__(self):
        return self.image_thumbnail.url


class Post(BaseModel):
    POST_STATUS_CHOICES = (
        ('BKP', _('Backup')),
        ('ACT', _('Active')),
        ('DIS', _('Disabled')),
    )

    title = models.CharField(max_length=200)
    body = models.TextField()
    slug = models.SlugField(max_length=200, blank=True, unique=True)
    status = models.CharField(max_length=3, choices=POST_STATUS_CHOICES)
    publication_datetime = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    category = models.ForeignKey(PostCategory, on_delete=models.CASCADE)
    image = models.ForeignKey(Image, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['-publication_datetime']

    def __str__(self):
        return f'"{self.title}" by {self.author.username}'

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title) if not self.slug else self.slug
        return super().save(*args, **kwargs)

    @property
    def image_url(self):
        return self.image.image.url

blog/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Post


class PostListView(ListView):
    template_name = 'blog/blog_list.html'
    model = Post
    paginate_by = 10


class PostDetailView(DetailView):
    template_name = 'blog/post.html'
    model = Post
    context_object_name = 'post'
    slug_url_kwarg = 'post_slug'

    def get_object(self, post_month, post_slug):
        return self.model.objects.get(
            slug=post_slug,
            publication_datetime__icontains=f'-{post_month}-'
        )

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(**kwargs)
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  {% for post in object_list %}
    <a href="{% url 'blog:post' post_month=post.publication_datetime|date:'n' post_slug=post.slug %}"><h3>{{ post.title }}</h3></a><hr>
    {% if post.image %}<img src="{{ post.image_url }}" alt="{{ post.title }}">{% endif %}
    <p>Posted on {{ post.publication_datetime }}</p>
    <p>{{ post.body|safe|truncatechars:100 }}</p>
    <ul class="list-inline">
      {% for tag in post.tags.all %}
        <li class="list-inline-item text-info">#{{ tag }}</li>
      {% empty %}
        <p class="text-muted">No tags</p>
      {% endfor %}
    </ul>
  {% endfor %}
  <div class="pagination">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
      {% endif %}

      <span class="current">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
      </span>

      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
      {% endif %}
    </span>
  </div>
</div>
{% endblock %}

blog/templates/blog/post.html
{% extends 'base.html' %}

{% block main %}
<div class="container">
  <h1>{{ post.title }}</h1>
  {% if post.image %}<p><img src="{{ post.image_url }}" alt="{{ post.title }}"></p>{% endif %}
  <p>{{ post.publication_datetime }}</p>
  <p>{{ post.body|safe }}</p>
  <ul class="list-inline">
    {% for tag in post.tags.all %}
      <li class="list-inline-item text-info">#{{ tag }}</li>
    {% empty %}
      <p class="text-muted">No tags</p>
    {% endfor %}
  </ul>
</div>

{% endblock %}